---
title: "New Orleans"
output:
  pdf_document: default
  html_document: default
date: "2024-04-15"
---

# Libraries
```{r}
library(dplyr)
library(tidyverse)
library(ggplot2)
library(pROC)
library(caret)
library(recipes)
library(tidymodels)
library(tidytext)
library(wordcloud)
library(textdata)
library(igraph)
library(ggraph)
library(widyr)
library("jsonlite")
library(plm)
library(RTextTools)
library(SnowballC)
```
## Read in the data
```{r}
#airbnb_test_og <- read_csv("data/airbnb-project-msba-kaggle-test.csv")

df_og <- read_csv("/Users/kindyl/Desktop/airbnb-project-msba-kaggle-train.csv")


#no_test_df <- airbnb_test_og %>% 
  #filter(city %in% c("new-orleans", "New Orleans"))

no_train <- df_og %>% 
  filter(city %in% c("new-orleans", "New Orleans"))

```
```{r}
glimpse(df_og)
```

#### Little bit of cleaning
```{r}
# Remove dollar signs
remove_dollar_sign <- c("price", "extra_people", "weekly_price", "monthly_price")

no_train <-
  no_train %>%
  mutate_at(remove_dollar_sign, ~str_replace_all(., pattern="\\$", replacement="")) %>%
  mutate_at(remove_dollar_sign, ~str_replace_all(., pattern=",", replacement="")) %>%
  mutate_at(remove_dollar_sign, ~as.numeric(.))


# Remove percentage signs
remove_pct_sign <- c("host_response_rate", "host_acceptance_rate")

no_train <-
  no_train %>%
  mutate_at(remove_pct_sign, ~str_replace_all(., pattern="\\%", replacement="")) %>%
  mutate_at(remove_pct_sign, ~as.numeric(.)) %>%
  mutate_at(remove_pct_sign, ~./100)

# Making a column called description_length
# df_train$description_length <- nchar(df_train$description)


#### Getting daily price for columns that only have weekly or monthly price
no_train <- no_train %>%
  mutate(
    price = ifelse(is.na(price) & !is.na(weekly_price), weekly_price / 7,
                   ifelse(is.na(price) & is.na(weekly_price), monthly_price / 30, price))
  )

glimpse(no_train)
```
### Initial Cleaning Test Data
```{r}
#remove_dollar_sign <- c("price", "extra_people", "weekly_price", "monthly_price")

#no_test_df <-
  #no_test_df %>%
 # mutate_at(remove_dollar_sign, ~str_replace_all(., pattern="\\$", replacement="")) %>%
  #mutate_at(remove_dollar_sign, ~str_replace_all(., pattern=",", replacement="")) %>%
  #mutate_at(remove_dollar_sign, ~as.numeric(.))


# Remove percentage signs
#remove_pct_sign <- c("host_response_rate", "host_acceptance_rate")

#no_test_df <-
  #no_test_df %>%
  #mutate_at(remove_pct_sign, ~str_replace_all(., pattern="\\%", replacement="")) %>%
  #mutate_at(remove_pct_sign, ~as.numeric(.)) %>%
  #mutate_at(remove_pct_sign, ~./100)


#Length of description column
# df_test$description_length <- nchar(df_test$description)

#### Getting daily price for columns that only have weekly or monthly price
#no_test_df <- no_test_df %>%
  #mutate(
    #price = ifelse(is.na(price) & !is.na(weekly_price), weekly_price / 7,
  #                 ifelse(is.na(price) & is.na(weekly_price), monthly_price / 30, price))
  #)


# airbnb_test$price_missing <- ifelse(is.na(airbnb_test$price), 1, 0)

```

```{r}
nas_per <- colSums(is.na(no_train))

nas_per <- nas_per[order(-nas_per)]
```

# Cleaning 
```{r}
no_train <-no_train %>% 
  mutate_if(is.logical, as.numeric) %>% 
  mutate(cleaning_fee = ifelse(is.na(cleaning_fee), 0, cleaning_fee)) %>%
 mutate(cleaning_fee = as.numeric(cleaning_fee)) %>% 
  mutate(host_is_superhost = ifelse(is.na(host_is_superhost), 0, host_is_superhost)) %>% 
 mutate(log_price = ifelse(price == 0, 0, round(log(price), 4))) %>% 
 mutate(host_response_time = ifelse(is.na(host_response_time), "N/A", host_response_time)) %>% 
 mutate(host_response_time = factor(host_response_time, levels = c("within an hour", "within a few hours", "within a day", "a few days or more", "N/A")))

rec <- recipe(~ ., data = no_train) %>%
 step_impute_median(accommodates, -96) %>%  # Impute mean for "accommodates" 
 step_impute_mode(neighbourhood_cleansed) %>% 
 step_impute_median(beds, -96) %>%  # Impute mean for "beds"
 step_impute_median(bedrooms, -96) %>%  # Impute mean for "bedrooms"
 step_impute_median(price, -96) %>% 
 step_impute_median(log_price, -96) %>%
 step_impute_median(review_scores_rating, -96) %>% 
 step_impute_median(review_scores_accuracy, -96) %>% 
  step_impute_median(host_acceptance_rate, -96) %>%
  step_impute_median(host_response_rate, -96) 

# Apply the recipe to the data
no_train <- prep(rec) %>% bake(new_data = NULL)
```

```{r}
#na.omit(df$price)
no_train <- no_train %>% 
  mutate_if(is.logical, as.numeric) %>% 
  #mutate(cleaning_fee = ifelse(is.na(cleaning_fee), 0, cleaning_fee)) %>%
  #mutate(cleaning_fee = as.numeric(cleaning_fee)) %>% 
  mutate(host_is_superhost = ifelse(is.na(host_is_superhost), 0, host_is_superhost)) %>% 
  mutate(log_price = ifelse(price == 0, 0, round(log(price), 4))) %>% 
  mutate(host_response_time = ifelse(is.na(host_response_time), "N/A", host_response_time)) %>% 
  mutate(host_response_time = factor(host_response_time, levels = c("within an hour", "within a few hours", "within a day", "a few days or more", "N/A")))

# rec <- recipe(~ ., data = no_train) %>%
#   step_impute_median(accommodates, -96) %>%  # Impute mean for "accommodates" 
#   step_impute_mode(neighbourhood_cleansed) %>% 
#   step_impute_median(beds, -96) %>%  # Impute mean for "beds"
#   step_impute_median(bedrooms, -96) %>%  # Impute mean for "bedrooms"
#   step_impute_median(price, -96) %>% 
#   step_impute_median(log_price, -96) %>%
#   step_impute_median(review_scores_rating, -96) %>% 
#   step_impute_median(review_scores_accuracy, -96) %>% 
#   step_impute_median(host_acceptance_rate, -96) %>%
#   step_impute_median(host_response_rate, -96) 

# # Apply the recipe to the data
# no_train <- prep(rec) %>% bake(new_data = NULL)

# View the processed data
glimpse(no_train)
no_train <- no_train %>%
  mutate(high_booking = as.factor(high_booking))

# Print the result
head(no_train)
```
## Word Counts
```{r}
no_train <- no_train %>%
  mutate(space_word_count = str_count(space, "\\b[A-Za-z0-9]{2,}\\b")) %>% 
  mutate(desc_word_count = str_count(description, "\\b[A-Za-z0-9]{2,}\\b")) %>%
  mutate(name_word_count = str_count(name, "\\b[A-Za-z0-9]{2,}\\b"))
```

## Dummy Variable Things
```{r}
#host_response_time
unique_values <- no_train %>%
  distinct(host_response_time) %>%
  pull(host_response_time)

unique_values

no_train <- no_train %>%
  mutate(
    response_within_an_hour = as.integer(host_response_time == "within an hour"),
    response_within_a_few_hours = as.integer(host_response_time == "within a few hours"),
    response_within_a_day = as.integer(host_response_time == "within a day"),
    response_a_few_days = as.integer(host_response_time == "a few days or more")
  )
```

## Find Listing ID
```{r}
no_train <- no_train %>%
  mutate(listing_id = as.numeric(str_extract(listing_url, "(?<=rooms/)\\d+")))
```
##Remove Unecessary Columns
```{r}
#Remove columns
no_train <- no_train %>% 
  select(-state, -summary, -listing_url, -picture_url, - host_url, -host_about, -host_picture_url, -street, -neighbourhood,-neighbourhood_group_cleansed,-market,-weekly_price, -monthly_price, -review_scores_cleanliness,-review_scores_accuracy, -review_scores_checkin,-review_scores_communication, -review_scores_location, -review_scores_value,-requires_license, -license, -jurisdiction_names, -experiences_offered, -notes, -thumbnail_url, -medium_url, -xl_picture_url, -host_thumbnail_url, -host_neighbourhood, -host_listings_count, -country_code, -cleaning_fee, -require_guest_profile_picture, -require_guest_phone_verification, -is_business_travel_ready, -minimum_minimum_nights, -maximum_minimum_nights, -minimum_maximum_nights, -maximum_maximum_nights,-minimum_nights_avg_ntm, -maximum_nights_avg_ntm,-bathrooms_text,-region_id, -region_name, -region_parent_id, region_parent_name, -host_listing_count, -latitude_cleansed, -longitude_cleansed)

no_train <- no_train %>% 
  select(-city)

no_train <- no_train %>% 
  select(-host_name, -host_id, - host_location)


print(no_train)
```

```{r}
# Function to check for amenities
check_amenity <- function(amenities, amenity_name) {
  # Remove curly braces and split the string by commas
  amenities_list <- strsplit(gsub("[{}]", "", amenities), ",")[[1]]
  # Trim whitespace and remove quotes
  amenities_list <- str_trim(gsub('"', '', amenities_list))
  # Check if the amenity is in the list
  return(amenity_name %in% amenities_list)
}

# Create new columns for each amenity
no_train <- no_train %>%
  mutate(
    has_WiFi = sapply(amenities, function(x) {
      check_amenity(x, "Wi-Fi") || check_amenity(x, "Wireless Internet") || 
      check_amenity(x, "Ethernet Connection") || check_amenity(x, "Free wifi")
    }),
    has_AC = sapply(amenities, function(x) {
      check_amenity(x, "Air Conditioning") || check_amenity(x, "Central air conditioning") || 
      check_amenity(x, "Window AC unit")
    }),
    has_Pool = sapply(amenities, function(x) {
      check_amenity(x, "Pool") || check_amenity(x, "Private outdoor pool")
    }),
    has_Waterfront = sapply(amenities, function(x) {
      check_amenity(x, "Waterfront")
    }),
    has_HotTub = sapply(amenities, function(x) {
      check_amenity(x, "Hot Tub")
    })
  ) %>% 
  mutate(
    has_WiFi = ifelse(has_WiFi == TRUE, 1, 0),
    has_AC = ifelse(has_AC == TRUE, 1, 0),
    has_Pool = ifelse(has_Pool == TRUE, 1, 0),
    has_Waterfront = ifelse(has_Waterfront == TRUE, 1, 0),
    has_HotTub = ifelse(has_HotTub == TRUE, 1, 0)
  ) %>% 
  select(-amenities)
```

```{r}
table(no_train$has_WiFi)

```

# Map of New Orleans High Booking
```{r}
near_station <- recipe(~., data = no_train) %>%
  step_geodist(
    lat = latitude, lon = longitude, log = FALSE,
    ref_lat = 	29.959021, ref_lon = -90.065285
  ) %>%
  prep(training = no_train)

no_train <- bake(near_station, new_data = NULL) %>%
  arrange(geo_dist)


```

```{r}
#near_station2 <- recipe(~., data = no_test_df) %>%
  #step_geodist(
   # lat = latitude, lon = longitude, log = FALSE,
    #ref_lat = 	29.959021, ref_lon = -90.065285
  #) %>%
  #prep(training = no_test_df)

#yum_test <- bake(near_station, new_data = NULL) %>%
  #arrange(geo_dist)

```

```{r}
library(leaflet)

leaflet(data = no_train) %>%
  addTiles() %>% 
  addCircleMarkers(~longitude, ~latitude, 
  color = ~ifelse(high_booking == 1, "purple", "yellow"),
  radius = 2) %>%
  addCircleMarkers(
    lat = 29.959021, lng= -90.065285, 
    color = "red",  
    radius = 6, 
    popup = "Burbon Stree Hot Spot?"
  )
  
```

# Do everything to test data
```{r} 
# no_test_df <- no_test_df %>%
#    mutate(listing_id = as.numeric(str_extract(listing_url, "(?<=rooms/)\\d+"))) %>%
#   select(-state, -summary, -picture_url, - host_url, -host_about, -host_picture_url, -street, -neighbourhood,-neighbourhood_group_cleansed,-market,-weekly_price, -monthly_price, -review_scores_cleanliness,-review_scores_accuracy, -review_scores_checkin,-review_scores_communication, -review_scores_location, -review_scores_value,-requires_license, -license, -jurisdiction_names, -experiences_offered, -notes, -thumbnail_url, -medium_url, -xl_picture_url, -host_thumbnail_url, -host_neighbourhood, -host_listings_count, -country_code, -cleaning_fee, -require_guest_profile_picture, -require_guest_phone_verification, -is_business_travel_ready, -minimum_minimum_nights, -maximum_minimum_nights, -minimum_maximum_nights, -maximum_maximum_nights,-minimum_nights_avg_ntm, -maximum_nights_avg_ntm,-bathrooms_text,-region_id, -region_name, -region_parent_id, region_parent_name, -host_listing_count, -latitude_cleansed, -longitude_cleansed) 
#  
# no_test_df <- no_test_df %>% 
#   select(-city)
# 
# no_test_df <- no_test_df %>% 
#   select(-host_name, -host_id, - host_location)
# 
# no_test_df <- no_test_df %>%
#   mutate(space_word_count = str_count(space, "\\b[A-Za-z0-9]{2,}\\b")) %>% 
#   mutate(desc_word_count = str_count(description, "\\b[A-Za-z0-9]{2,}\\b")) %>%
#   mutate(name_word_count = str_count(name, "\\b[A-Za-z0-9]{2,}\\b"))
# 
# no_test_df <- no_test_df %>% 
#   mutate(
#     response_within_an_hour = as.integer(host_response_time == "within an hour"),
#     response_within_a_few_hours = as.integer(host_response_time == "within a few hours"),
#     response_within_a_day = as.integer(host_response_time == "within a day"),
#     response_a_few_days = as.integer(host_response_time == "a few days or more")
#   )
#   
#   
# # Function to check for amenities
# check_amenity <- function(amenities, amenity_name) {
#   # Remove curly braces and split the string by commas
#   amenities_list <- strsplit(gsub("[{}]", "", amenities), ",")[[1]]
#   # Trim whitespace and remove quotes
#   amenities_list <- str_trim(gsub('"', '', amenities_list))
#   # Check if the amenity is in the list
#   return(amenity_name %in% amenities_list)
# }
# 
# # Create new columns for each amenity
# no_test_df <- no_test_df %>%
#   mutate(
#     has_WiFi = sapply(amenities, function(x) {
#       check_amenity(x, "Wi-Fi") || check_amenity(x, "Wireless Internet") || 
#       check_amenity(x, "Ethernet Connection") || check_amenity(x, "Free wifi")
#     }),
#     has_AC = sapply(amenities, function(x) {
#       check_amenity(x, "Air Conditioning") || check_amenity(x, "Central air conditioning") || 
#       check_amenity(x, "Window AC unit")
#     }),
#     has_Pool = sapply(amenities, function(x) {
#       check_amenity(x, "Pool") || check_amenity(x, "Private outdoor pool")
#     }),
#     has_Waterfront = sapply(amenities, function(x) {
#       check_amenity(x, "Waterfront")
#     }),
#     has_HotTub = sapply(amenities, function(x) {
#       check_amenity(x, "Hot Tub")
#     })
#   ) %>% 
#   mutate(
#     has_WiFi = ifelse(has_WiFi == TRUE, 1, 0),
#     has_AC = ifelse(has_AC == TRUE, 1, 0),
#     has_Pool = ifelse(has_Pool == TRUE, 1, 0),
#     has_Waterfront = ifelse(has_Waterfront == TRUE, 1, 0),
#     has_HotTub = ifelse(has_HotTub == TRUE, 1, 0)
#   ) %>% 
#   select(-amenities)
```


##Mode Calc
```{r}
calculate_mode <- function(x) {
  ux <- unique(x)
  ux[which.max(tabulate(match(x, ux)))]
}

# Calculate mode for each variable for each listing_id
nola_train <- no_train %>%
  group_by(listing_id) %>%
  summarise(across(everything(), calculate_mode))
```


```{r}
# calculate_mode <- function(x) {
#   ux <- unique(x)
#   ux[which.max(tabulate(match(x, ux)))]
# }
# 
# # Calculate mode for each variable for each listing_id
# nola_test <- no_test_df %>%
#   group_by(listing_id) %>%
#   summarise(across(everything(), calculate_mode))
# 
# # Display the result
# glimpse(nola_test)
```

 
# EDA (much cooler)
```{r}
library(corrplot)

numeric_data <- no_train %>% 
  select(where(is.numeric))
cor_matrix <- cor(numeric_data)
# Plot the correlation matrix
corrplot(cor_matrix, method = "circle")
```

#First EDA
## Listing ID EDA
```{r}
listing_count <- no_train %>%
  group_by(listing_id) %>%
  summarize(count = n())

summawize <- no_train %>%
  group_by(listing_id) %>%
  summarize(
    total = n(),  # Total number of bookings for each listing_id
    high_booking_count = sum(high_booking == 1, na.rm = TRUE),  # Count of high_booking = 1
    percentage_high_booking = (high_booking_count / total) * 100  # Calculate percentage
  ) %>% 
  arrange(desc(percentage_high_booking))
summawize
```

```{r}
calculate_mode <- function(x) {
  ux <- unique(x)
  ux[which.max(tabulate(match(x, ux)))]
}

nola_train <- no_train %>%
  group_by(listing_id) #%>%
  #summarise(across(-c(host_verifications, -neighbourhood_cleansed), calculate_mode))



```

##BOXPLOTS
```{r}

```
```{r}
#Boxplot of price and high_booking
Price_Booking_Boxplot <- ggplot(no_train, aes(x = high_booking, y = price)) +
  geom_boxplot() +
  labs(title = "Boxplot of Price by High Booking Status Zoomed In",
       x = "High Booking Status", 
       y = "Price") +
  theme_bw()+
  coord_cartesian(ylim = c(100, 900))

Price_Booking_Boxplot

Price_Booking_Boxplot2 <- ggplot(no_train, aes(x = high_booking, y = price)) +
  geom_boxplot() +
  labs(title = "Boxplot of Price by High Booking Status",
       x = "High Booking Status", 
       y = "Price") +
  theme_bw()

Price_Booking_Boxplot2

```
```{r}
#Sort by price descending + ascending
price_desc <- no_train %>%

arrange(desc(price))

price_desc
```
```{r}
library(corrplot)
numeric_data <- no_train %>%
  select(where(is.numeric)) %>%
  select_if(~ sd(.) != 0)

numeric_data <- numeric_data %>% 
  select(where(is.numeric))

cor_matrix <- cor(numeric_data, use = "pairwise.complete.obs")
corrplot(cor_matrix, method = "circle")
cor_data <- melt(cor_matrix)

# Plot using ggplot2
ggplot(cor_data, aes(x = Var1, y = Var2, fill = value)) +
  geom_tile() +
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", midpoint = 0) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1))
```
```{r}

boxplots$review_scores_rating <- cut(boxplots$review_scores_rating,
                         breaks = seq(0, 100, by = 10),
                         labels = c("0-10", "11-20", "21-30", "31-40", "41-50", "51-60", "61-70", "71-80", "81-90", "91-100"),
                         include.lowest = TRUE)

p <- ggplot(boxplots, aes(x = factor(review_scores_rating), y = price)) +
    geom_boxplot() +
    labs(title = "RSR s Price", x = "Review Scores Rating", y = "Price") +
    theme_bw()
p

```




# Models

##Split
```{r}
set.seed(80)
n1=nrow(nola_train)
nt1=round(nrow(nola_train)*.8)
indexes = sample(n1, nt1)
df_analysis = nola_train[indexes,]
df_assesment = nola_train[-indexes,]
```

##XG. Boost
```{r}
airbnb_recipe <- 
  recipe(high_booking ~ review_scores_rating + host_is_superhost + host_response_time + beds + log_price + host_acceptance_rate + host_response_rate + geo_dist + square_feet  + host_identity_verified + response_within_a_day + guests_included + host_total_listings_count + host_identity_verified + host_has_profile_pic + cancellation_policy + has_HotTub, data = df_analysis) %>% 
  step_string2factor(all_nominal(), skip = TRUE) %>%
  #step_other(neighbourhood_cleansed, threshold = 0.01, skip = TRUE) %>%
  step_nzv(all_predictors())

airbnb_xg <- 
  airbnb_recipe %>% 
  step_dummy(all_predictors(), -all_numeric(), -all_outcomes())
```

```{r}
hist(my_log_results$predictedProbabilities, breaks = 20, main = "Distribution of Predicted Probabilities")
```

#logistic
```{r}

```

```{r}
airbnb_recipe1 <-
  recipe(high_booking ~ review_scores_rating + host_is_superhost + beds + log_price + geo_dist + square_feet  + host_identity_verified  + guests_included + host_has_profile_pic + cancellation_policy + has_HotTub + has_Pool + has_WiFi + has_Waterfront + host_acceptance_rate + instant_bookable + guests_included + host_total_listings_count + response_within_a_day, data = df_analysis) %>%
  #step_impute_median(bedrooms) %>% # Median imputations
  # convert categorical variables to factors
  step_string2factor(all_nominal(), skip = TRUE) %>% # skip = TRUE means that the step is applied when making the training set but is skipped when data are being predicted => high_booking_rate won't be in new data
  # combine low frequency factor levels
  step_other(all_nominal(), threshold = 0.01, skip = TRUE) %>%
  #step_interact(~ host_acceptance_rate:host_response_rate) %>% 
  # remove no variance predictors which provide no predictive information
  step_nzv(all_predictors())

# Apply imputations to test set
my_log_method <-
  logistic_reg() %>%
  set_engine("glm")

my_log_workflow1 <-
  workflow() %>%
  add_model(my_log_method) %>%
  add_recipe(airbnb_recipe1)
```


```{r}
my_log_fit <- 
fit(my_log_workflow1, data = df_assesment)
  
tidy(my_log_fit) %>% 
  mutate(exp_coef = exp(estimate))

tidy(my_log_fit)

my_log_fit %>%
  extract_fit_parsnip() %>%
  performance::check_collinearity()

my_log_results <- 
  predict(my_log_fit, df_assesment, type = 'prob') %>% 
  pluck(2) %>% 
  bind_cols(df_assesment, predictedProbabilities = .) %>%
  mutate(predictedClass = as.factor(ifelse(predictedProbabilities > 0.5, 1, 0)))

conf_mat_results <- conf_mat(my_log_results, truth = high_booking, estimate = predictedClass)  
conf_mat <- summary(conf_mat_results, event_level = 'second')

roc_auc(my_log_results, truth = high_booking, predictedProbabilities, event_level = 'second')

conf_mat_results
conf_mat
```
```{r}
true_positives <- my_log_results %>%
  filter(high_booking == 1 & predictedClass == 1)
```

```{r}
set.seed(80)
n1=nrow(no_train)
nt1=round(nrow(no_train)*.8)
indexes = sample(n1, nt1)
df_analysis2 = no_train[indexes,]
df_assesment2 = no_train[-indexes,]

airbnb_recipe3 <-
  recipe(high_booking ~ review_scores_rating + host_is_superhost + beds + log_price + geo_dist + square_feet  + host_identity_verified  + guests_included + host_has_profile_pic + cancellation_policy + has_HotTub + has_Pool + has_WiFi + has_Waterfront + host_acceptance_rate +instant_bookable, data = df_analysis2) %>%
  step_impute_median(beds, has_HotTub, has_Pool, square_feet) %>% # Median imputations
  # convert categorical variables to factors
  step_string2factor(all_nominal(), skip = TRUE) %>% # skip = TRUE means that the step is applied when making the training set but is skipped when data are being predicted => high_booking_rate won't be in new data
  # combine low frequency factor levels
  step_other(all_nominal(), threshold = 0.01, skip = TRUE) %>%
  #step_interact(~ host_acceptance_rate:host_response_rate) %>% 
  # remove no variance predictors which provide no predictive information
  step_nzv(all_predictors())

# Apply imputations to test set
my_log_method <-
  logistic_reg() %>%
  set_engine("glm")

my_log_workflow3 <-
  workflow() %>%
  add_model(my_log_method) %>%
  add_recipe(airbnb_recipe3)

my_log_fit3 <- 
fit(my_log_workflow1, data = df_assesment2)
  
tidy(my_log_fit3) %>% 
  mutate(exp_coef = exp(estimate))

tidy(my_log_fit3)

my_log_fit3 %>%
  extract_fit_parsnip() %>%
  performance::check_collinearity()

my_log_results3 <- 
  predict(my_log_fit, df_assesment2, type = 'prob') %>% 
  pluck(2) %>% 
  bind_cols(df_assesment2, predictedProbabilities = .) %>%
  mutate(predictedClass = as.factor(ifelse(predictedProbabilities > 0.5, 1, 0)))

conf_mat_results3 <- conf_mat(my_log_results3, truth = high_booking, estimate = predictedClass)  
conf_mat3 <- summary(conf_mat_results, event_level = 'second')

roc_auc(my_log_results3, truth = high_booking, predictedProbabilities, event_level = 'second')

conf_mat_results3
conf_mat3
```

##XGBOOST with geo_dist
```{r}
xgboost_method_all <-
  boost_tree(mode = "classification", trees = 100) %>%
  set_engine("xgboost")

xgboost_workflow_all <-
  workflow() %>%
  add_recipe(airbnb_xg) %>%
  add_model(xgboost_method_all)


set.seed(80)
fit_xgboost_all <- fit(xgboost_workflow_all, df_analysis)

fit_xgboost_all %>%
  extract_fit_parsnip() %>%
  vip::vip(num_features = 10)

results <-
  predict(fit_xgboost_all, df_assesment, type = "prob") %>%
  pluck(2) %>%
  bind_cols(df_assesment, Predicted_Probability = .)

roc_auc(results, truth = high_booking, Predicted_Probability, event_level = 'second')

roc_curve <- roc(results$high_booking, results$Predicted_Probability)

# Plot ROC curve
plot(roc_curve, main = "ROC Curve", col = "blue")
```

```{r}
table(no_train$high_booking)
```
```{r}
glimpse(df_analysis)
```


```{r}
log.model<-glm(high_booking ~ log_price + geo_dist + review_scores_rating + host_acceptance_rate + accommodates, data = df_analysis, family=binomial)
log_sum<- summary(log.model)

# Logistic Regression Predictions
logprob<-predict(log.model, newdata=df_assesment, type="response")
head(logprob,3)


logpred=rep(0, nrow(df_assesment))

logpred[logprob>=.5]=1
logpred=as.factor(logpred)
head(logpred,3)

cm=confusionMatrix(data=logpred, reference=as.factor(df_assesment$high_booking))
cm
roc.test = roc(df_assesment$high_booking ~ logprob, plot = TRUE, print.auc = TRUE)

roc.test
```

```{r}
p_values <- log_sum$coefficients[, "Pr(>|z|)"]
p_values
```

